// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFuZFQ8cBsZ1FUvhyrfc46j2HYbiuq8c',
    appId: '1:915402983493:web:d25ae31ccc770fb91c3b2c',
    messagingSenderId: '915402983493',
    projectId: 'e-book-store-83a48',
    authDomain: 'e-book-store-83a48.firebaseapp.com',
    storageBucket: 'e-book-store-83a48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDm4MCWqNdP5Q7EMBRtuQZ2uMMdAJtgfY',
    appId: '1:745546316978:android:40683bd9b62405b3151dab',
    messagingSenderId: '745546316978',
    projectId: 'book-8ae0e',
    storageBucket: 'book-8ae0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wEHXQQdG-Gaz4Q1DYBmr34BwPYwOuzU',
    appId: '1:915402983493:ios:9c47fc0a0af6f9c91c3b2c',
    messagingSenderId: '915402983493',
    projectId: 'e-book-store-83a48',
    storageBucket: 'e-book-store-83a48.appspot.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wEHXQQdG-Gaz4Q1DYBmr34BwPYwOuzU',
    appId: '1:915402983493:ios:6088b94a0449f5761c3b2c',
    messagingSenderId: '915402983493',
    projectId: 'e-book-store-83a48',
    storageBucket: 'e-book-store-83a48.appspot.com',
    iosBundleId: 'com.example.eBook.RunnerTests',
  );
}